"""recipes table

Revision ID: 9679d18f5df7
Revises: bcf068db1129
Create Date: 2026-09-05 17:53:55.828226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9679d18f5df7'
down_revision = 'bcf068db1129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Numeric(precision=10, scale=1), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='recipedifficulty'), nullable=True))
        batch_op.add_column(sa.Column('servings_text', sa.String(length=60), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('servings_text')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('duration')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
